#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_PATH="$SCRIPT_DIR/data/openclaw.json"
COMPOSE_PATH="$SCRIPT_DIR/docker-compose.yml"
README_PATH="$SCRIPT_DIR/README.md"

python3 - "$CONFIG_PATH" "$COMPOSE_PATH" "$README_PATH" <<'PY'
from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

config_path = Path(sys.argv[1])
compose_path = Path(sys.argv[2])
readme_path = Path(sys.argv[3])


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


config = load_json(config_path)
compose_text = compose_path.read_text() if compose_path.exists() else ""

defaults = config.get("agents", {}).get("defaults", {})
gateway = config.get("gateway", {})
plugins = config.get("plugins", {}).get("entries", {})
models = defaults.get("models", {})

primary_model = defaults.get("model", {}).get("primary", "Not configured")
gateway_mode = gateway.get("mode", "local")
gateway_bind = gateway.get("bind", "loopback")
enabled_plugins = ", ".join(
    name for name, plugin in plugins.items() if isinstance(plugin, dict) and plugin.get("enabled")
) or "none"
available_models = "\n".join(
    f"- {model.get('alias', model_id)} (`{model_id}`)"
    for model_id, model in models.items()
)
if not available_models:
    available_models = "- None configured"

port_matches = re.findall(r'^\s*-\s*"(\d+):\d+"', compose_text, flags=re.MULTILINE)
ports = "\n".join(f"- `{port}`" for port in port_matches) or "- `48728`"

known_keys = [
    ("GEMINI_API_KEY", "Gemini (Google)"),
    ("APIFY_API_KEY", "Apify"),
    ("ELEVENLABS_API_KEY", "ElevenLabs"),
    ("KALSHI_API_KEY_ID", "Kalshi"),
    ("OPENAI_API_KEY", "OpenAI"),
    ("ANTHROPIC_API_KEY", "Anthropic"),
    ("XAI_API_KEY", "xAI (Grok)"),
    ("NEXOS_API_KEY", "Nexos"),
]
configured_keys = [
    f"- {label}"
    for env_var, label in known_keys
    if re.search(rf"^\s*-\s*{re.escape(env_var)}=", compose_text, flags=re.MULTILINE)
]
if not configured_keys:
    configured_keys = ["- None"]

readme = f"""# OpenClaw — Local Setup

Single local OpenClaw instance. One setup, one place: `~/Desktop/openclaw`.

## Quick Start

```bash
cd ~/Desktop/openclaw
docker compose up -d
```

Open: **http://localhost:48728**

No login required — auto-authenticates locally.

## Stop / Restart

```bash
docker compose down       # stop
docker compose restart    # restart
docker compose logs -f    # follow logs
```

## Current Configuration

| Setting | Value |
|---|---|
| **Default Model** | {primary_model} |
| **Gateway Mode** | {gateway_mode} |
| **Gateway Bind** | {gateway_bind} |
| **Dashboard URL** | http://localhost:48728 |
| **Gateway Token** | openclaw-local |

## Ports

{ports}

| Port | Purpose |
|---|---|
| `48728` | Web dashboard (main entry point) |
| `18789` | WebSocket gateway |
| `18791` | Secondary |

## Available Models

{available_models}

## Configured API Keys

{chr(10).join(configured_keys)}

## Enabled Plugins

{enabled_plugins}

## File Structure

```
openclaw/
├── Dockerfile             # Local image overlay (adds ffmpeg/fonts for video skills)
├── docker-compose.yml     # Main config — edit ports, env vars, keys here
├── server.mjs             # Patched proxy (auto-auth, fixed port)
├── update-readme.sh       # Regenerates this README
├── data/
│   ├── openclaw.json      # OpenClaw runtime config (models, gateway, plugins)
│   ├── workspace/         # Agent workspace files
│   ├── agents/            # Agent state and sessions
│   └── credentials/       # Credentials (restricted permissions)
├── skills/                # Custom skills mounted into container
├── .env                   # Local env (Kalshi key IDs etc.)
└── .kalshi_private_key.pem # Local Kalshi private key (not committed)
```

## Adding API Keys

Edit `docker-compose.yml` under `environment`:

```yaml
- OPENAI_API_KEY=sk-...
- ANTHROPIC_API_KEY=sk-ant-...
- GEMINI_API_KEY=...
- XAI_API_KEY=...
```

Then restart: `docker compose restart`

## Changing Default Model

Edit `data/openclaw.json`:

```json
"agents": {{
  "defaults": {{
    "model": {{
      "primary": "Gemini 3 Flash Preview"
    }}
  }}
}}
```

Then restart: `docker compose restart`

---
*Auto-generated by `update-readme.sh` — last updated: {datetime.now().strftime("%Y-%m-%d %H:%M")}*
"""

readme_path.write_text(readme)
PY

echo "README.md updated."
